# TODO(@johnletey): Figure out the other query tags
query (
  $num: Int
) {
  transactions(
    tags: [
      {
        name: "Exchange",
        values: "Verto"
      }
    ]
    first: $num
  ) {
    edges {
      node {
        block {
          timestamp
        }
        tags {
          name
          value
        }
      }
    }
  }
}
