query (
  $owners: [String!]
  $num: Int
  $cursor: String
) {
  transactions(
    owners: $owners
    tags: [
      {
        name: "Exchange",
        values: "Verto"
      }
    ]
    first: $num
    after: $cursor
  ) {
    pageInfo {
      hasNextPage
    }
    edges {
      cursor
      node {
        id
        block {
          timestamp
        }
        tags {
          name
          value
        }
      }
    }
  }
}
