query {
  transactions(
    tags: [
      { name: "App-Name", values: "Verto" }
      { name: "Trading-Post-Genesis", values: "G" }
    ]
  ) {
    edges {
      node {
        owner {
          address
        }
      }
    }
  }
}
