query (
  $recipients: [String!]
) {
  transactions(
    recipients: $recipients
    tags: [
      { 
        name: "Exchange", 
        values: "Verto" 
      }
      { 
        name: "Trading-Post-Genesis", 
        values: "G" 
      }
    ]
  ) {
    pageInfo {
      hasNextPage
    }
    edges {
      cursor
      node {
        owner {
          address
        }
      }
    }
  }
}
