query {
  transactions(
    tags: [{ 
      name: "Exchange", 
      values: "Verto" 
    }]
    first: 5
  ) {
    edges {
      node {
        id
        quantity {
          ar
        }
      }
    }
  }
}
