query($owners: [String!], $recipients: [String!]) {
  transactions(
    owners: $owners
    recipients: $recipients
    tags: [
      { name: "Exchange", values: "Verto" }
      { name: "Type", values: "Genesis" }
    ]
    first: 1
  ) {
    edges {
      node {
        id
      }
    }
  }
}
