query($owners: [String!], $contractSrc: String!) {
  transactions(
    owners: $owners
    tags: [
      { name: "Exchange", values: "Verto" }
      { name: "Support", values: "PST" }
      { name: "Contract", values: $contractSrc }
    ]
  ) {
    edges {
      node {
        id
      }
    }
  }
}
