query {
  transactions(
    owners: ["pvPWBZ8A5HLpGSEfhEmK1A3PfMgB_an8vVS6L14Hsls"]
    tags: [
      {
        name: "App-Name",
        values: "Verto"
      }
      {
        name: "Support",
        values: "PST"
      }
    ]
  ) {
    edges {
      node {
        id
      }
    }
  }
}
