name: build

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1

      - name: Install yarn
        run: npm i -g yarn

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Export
        run: yarn export
      
      - name: Start server
        run: | 
          cd __sapper__/export 
          python -m SimpleHTTPServer 8080 &
          
      - name: Run Lighthouse
        uses: BrunnerLivio/lighthouse-action@master
        id: lighthouse
        with:
          urls: http://localhost:8080/
      - name: Comment output on PR
        if: github.event_name == 'pull_request'
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: "Lighthouse score \nPerformance: ${{ steps.lighthouse.outputs.performance }}\nAccessibility: ${{ steps.lighthouse.outputs.accessibility }}\nBest Practices: ${{ steps.lighthouse.outputs.practices }}\nSEO: ${{ steps.lighthouse.outputs.seo }}\n            PWA: ${{ steps.lighthouse.outputs.pwa }}\n"
          
