name: build

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1

      - name: Install yarn
        run: npm i -g yarn

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Export
        run: yarn export
      
      - name: Start server
        run: | 
          cd __sapper__/export 
          python -m SimpleHTTPServer &
          
      - name: Run Lighthouse
        uses: foo-software/lighthouse-check-action@master
        with:
          accessToken: ${{ secrets.LIGHTHOUSE_CHECK_GITHUB_ACCESS_TOKEN }}
          author: ${{ github.actor }}
          urls: http://localhost:8080/
          prCommentEnabled: true
          
